### ISSUE TITLE
Errors on compilation

### ISSUE THREAD

**Issue by ranperry** [pekingduck/metadsf#1]
Running configure return no errors. When compiling, I get the following errors:

undefined reference to `TagLib::String::String()'
undefined reference to`TagLib::String::toCString(bool) const'
undefined reference to `TagLib::String::size() const'

Any ideas?

**Comment by pekingduck** [comment]
What OS are you trying to compile on?

**Comment by ranperry** [comment]
Ubuntu 14.04

**Comment by pekingduck** [comment]
OK I just installed Ubuntu 14.04 on my Mac and ran into similar errors. I guess it's because of some Makefile problem and will fix it later. Anyway I have compiled a binary manually and put it under the release section. Feel free to try it.

Thanks for the bug report!

**Comment by ranperry** [comment]
Thanks. No matter what I do, I get the following error:

metadsf: error while loading shared libraries: libtag.so.1: cannot open shared object file: No such file or directory

I even copied libtag.so.1 to the same directory metadsf is located.

**Comment by pekingduck** [comment]
Do you happen to be running 64-bit Ubuntu? I just realised my Ubuntu VM was 32-bit. Anyway I just  uploaded a new 64-bit binary that hopefully will work for you!

**Comment by ranperry** [comment]
Indeed. The new 64bit version works as expected. Thanks.
